# Data Audits

In [46]:
import pandas as pd
data_audit = pd.read_csv("../data/raw/upi_transactions_raw.csv")

print("--- Shape of the dataset ---")
print(data_audit.shape)

--- Shape of the dataset ---
(50000, 11)

In [47]:
print("--- Columns in the dataset ---")
print(data_audit.columns.tolist())

--- Columns in the dataset ---
['transaction_id', 'user_id', 'timestamp', 'amount', 'transaction_type', 'merchant_category', 'merchant_id', 'city', 'device_id', 'status', 'receiver_id']

In [48]:
print("--- First 5 rows of the dataset ---")
data_audit.head()

--- First 5 rows of the dataset ---

,transaction_id,user_id,timestamp,amount,transaction_type,merchant_category,merchant_id,city,device_id,status,receiver_id
0,TXN00037414,U01112,01-01-2026 00:08,289.59,P2M,Healthcare,M01383,Delhi,D00790,SUCCESS,M01383
1,TXN00029422,U01252,01-01-2026 00:11,77.56,P2M,Fuel,M00389,Ahmedabad,D01414,SUCCESS,M00389
2,TXN00026757,U00488,01-01-2026 00:11,154.65,P2P,P2P,NaN,Mumbai,D04419,SUCCESS,U01599
3,TXN00005630,U02139,01-01-2026 00:22,273.63,P2P,P2P,NaN,Ahmedabad,D03775,SUCCESS,U03408
4,TXN00009067,U02122,01-01-2026 00:27,93.49,P2P,P2P,NaN,Chennai,D03238,SUCCESS,U04199

In [49]:
print("--- Data types of the dataset ---")
print(data_audit.dtypes)

--- Data types of the dataset ---
transaction_id           str
user_id                  str
timestamp                str
amount               float64
transaction_type         str
merchant_category        str
merchant_id              str
city                     str
device_id                str
status                   str
receiver_id              str
dtype: object

In [58]:
print("--- Missing values in the dataset ---")
data_audit.isnull().sum()

--- Missing values in the dataset ---

transaction_id           0
user_id                  0
timestamp                0
amount                   0
transaction_type         0
merchant_category        0
merchant_id          17692
city                     0
device_id                0
status                   0
receiver_id              0
dtype: int64

In [65]:
print("--- Duplicate rows in the dataset ---")
print(data_audit.duplicated().sum())

--- Duplicate rows in the dataset ---
0

In [68]:
print("--- Summary statistics of the dataset ---")
data_audit.describe()

--- Summary statistics of the dataset ---

             amount
count  50000.000000
mean     288.158893
std      303.464056
min       10.000000
25%      112.610000
50%      200.725000
75%      356.680000
max     9020.200000

In [70]:
print("--- Overall summary of the dataset ---")
data_audit.describe(include='all')

--- Overall summary of the dataset ---

,transaction_id,user_id,timestamp,amount,transaction_type,merchant_category,merchant_id,city,device_id,status,receiver_id
count,50000,50000,50000,50000.000000,50000,50000,32308,50000,50000,50000,50000
unique,50000,5000,45418,NaN,2,11,1500,8,3035,3,6365
top,TXN00037414,U04461,11-02-2026 04:17,NaN,P2M,P2P,M00589,Pune,D00703,SUCCESS,M00589
freq,1,27,5,NaN,32308,17692,41,6673,67,47046,41
mean,NaN,NaN,NaN,288.158893,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,303.464056,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,112.610000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,200.725000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,356.680000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,9020.200000,NaN,NaN,NaN,NaN,NaN,NaN,NaN